### ISSUE TITLE
Operation as parameter

### ISSUE THREAD

**Issue by Pilapou** [pevers/rapid#1]
Return an unexpected error when we do an arithmetic operation in a parameter

**Comment by pevers** [comment]
This specific case is fixed in 0.1.4, but I discovered another one. Seems like ABB RAPID has case in-sensitive keywords. Even though it looks like basic, this is perfectly fine RAPID:

'cAsE 14: ...`

Created a new issue here https://github.com/pevers/rapid/issues/2
